import type { Metadata } from "next";
import {Manrope } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Navbar from "./components/Navbar/navbar"
import "./globals.css";


const manRope = Manrope({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${manRope.variable}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        <Toaster
          position="top-center"
          toastOptions={{
            style: {
              background: "#18181b",
              color: "#ffffff",
              border: "1px solid #3f3f46",
            },
          }}
        />
        {children}
        </body>
    </html>
  );
}
